AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Spring Boot 2 API - io.github.shreeshasa::aws-lambda-springboot2
Globals:
  Api:
    EndpointConfiguration: REGIONAL

Resources:
  AwsLambdaSpringboot2Function:
    Type: AWS::Serverless::Function
    Properties:
      Handler: io.github.shreeshasa.StreamLambdaHandler::handleRequest
      Runtime: java8
      CodeUri: .
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 30
      Events:
        ProxyResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
